### ISSUE TITLE
Verbosity of summary is too much for large warehouses & github actions

### ISSUE THREAD

**Issue by devon-seitz-cirrusmd** [InfuseAI/piperider#732]
**Is your feature request related to a problem? Please describe.**
There is a text limit to the comment that get published to Github actions. When running Piperider on more than 100+ tables, that comment/comparison markdown is too large for Github to accept. 

**Describe the solution you'd like**
I think the best way to handle would be to optionally reduce the verbosity of a summary report to only highlight the things/tables that have changed instead of all tables. This way the comment can be drastically shorter then the normal comparison summary.

**Describe alternatives you've considered**
I have tried using the piperider github action for comparison, and writing my own action steps using the github comment upload api, but the markdown for the summary is simply too large.

**Additional context**

**Comment by even-wei** [comment]
Hi folks,

Thanks for your feedback. 🙏
Let me briefly summarize the issues and explain the improvement on the way.

---

**1. comment/comparison markdown is too large for Github to accept**
We are working on new summary markdown, which highlights altered models, affected downstream, and metrics. It will be released on Thursday (6/15) and you can checkout this [gist](https://gist.github.com/infuseai-dev/9919580952751a47798198402ddb2339).

However, it still could be too large to fit in GitHub comments. We are working on replacing some parts in the summary with links to the reports on PipeRider Cloud. The top priority is to highlight changes to our users.

If anything important to you but is not shown in the summary, please let me know. So we can help you more and benefit the community in general.

---

**2. piperider compare could exclusively display the modified models**
Currently, we are implementing some features that improve `piperider compare`.
1. by default, `piperider compare` will profile models based on the tags in the target branch. So you don't need to add tags in the main branch in order to profile those models. This will be release on Thursday (6/15).
2. PipeRider will support dbt selector, so that you can use `piperider compare --select state:modified+ --state /tmp/base` to run PipeRider on models with code change and affected downsteam. And this should be released on 6/29.

By the way, PipeRider does not profile models without `piperider` tag by default after version 0.25. If all models are profiled in your environment, you can upgrade PipeRider, remove `.piperider/config.yml`, and run `piperider compare` directly. Check our post https://medium.com/inthepipeline/zero-config-code-review-and-data-profiling-tool-for-dbt-projects-8b6de40964b4

**Comment by devon-seitz-cirrusmd** [comment]
@DaveFlynn This is great! Do you know if the github action will be updated to allow the --modify

**Comment by DaveFlynn** [comment]
@devon-seitz-cirrusmd  I have contacted the development team and this will be updated very soon. I'll let you know when it is ready. Thanks!
